spring:
  application:
    name: ShoppingCart
  data:
    mongodb:
      uri: mongodb://root:example@localhost:27017/shoppingCart?authSource=admin
      authentication-database: admin
      database: shoppingCart
      
mongock:
  migration-scan-package: hr.ht.retail.shoppingCart.config.migrations