@localServer=http://localhost:8080
@server={{localServer}}
@id1=6679594516af2f4f562014f0
@id2=66788a4bd40709137bbeeb04

### Get all customers
GET {{server}}/v1/customers
Content-Type: application/json

### Get one customer for the particular Id
GET {{server}}/v1/customers/{{id1}}
Content-Type: application/json

### Create customer
POST {{server}}/v1/customers
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Doe",
  "email": "john.doe@email.com"
}

### Update customer for the particular Id
PUT {{server}}/v1/customers/{{id1}}
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Doe",
  "email": "doejohn@email.com"
}

### Delete customer for this particular id
DELETE {{server}}/v1/customers/{{id1}}
Content-Type: application/json