@localServer=http://localhost:8080
@server={{localServer}}
@id1=66758484a291af0f27d7f06e
@id2=66743641c754183a747c06bb

### Get all prices for the particular Id
GET {{server}}/v1/prices
Content-Type: application/json

### Get one price for the particular Id
GET {{server}}/v1/prices/{{id1}}
Content-Type: application/json

### Create price for the particular Id
POST {{server}}/v1/prices
Content-Type: application/json

{
  "type": "ONE_TIME",
  "value": 144.00,
  "recurrences": null
}

### Create price for the particular Id
POST {{server}}/v1/prices
Content-Type: application/json

{
  "type": "RECURRING",
  "value": 20.00,
  "recurrences": 13
}

### Create price for the particular Id
POST {{server}}/v1/prices
Content-Type: application/json

{
  "type": "RECURRING",
  "value": 100.00,
  "recurrences": 11
}

### Update price for the particular Id
PUT {{server}}/v1/prices/{{id1}}
Content-Type: application/json

{
  "type": "RECURRING",
  "value": 18.75,
  "recurrences": 24
}

### Delete price for this particular id
DELETE {{server}}/v1/prices/{{id1}}
Content-Type: application/json

